version: '3'
services:
  my_ros_container:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=$DISPLAY
    network_mode: host
